[theme]
name = "modern"
[theme.overrides]
separator = ""

[icons]
name = "awesome"
[icons.overrides]
time = ""

[[block]]
block = "focused_window"

[[block]]
block = "weather"
format = " {weather} {temp}°"
service = { name = "openweathermap", api_key = "$(cat ~/keys/openweathermap)", city_id="5206379", units="metric" }

[[block]]
block = "net"
device = "$(iw dev | awk '$1=="Interface"{print $2}')"
ssid = true
speed_up = false
speed_down = false

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GiB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = " {MFm}/{MTm} MiB"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "battery"
upower = true

[[block]]
block = "time"
interval = 60
format = "%e %B %Y - %H:%M:%S"
