theme = "plain"
icons = "awesome"

[[block]]
block = "weather"
format = "{weather} {temp}°, {wind} m/s {direction}"
service = { name = "openweathermap", api_key = "$(cat ~/keys/openweathermap)", city_id="5206379", units="metric" }

[[block]]
block = "net"
device = "$(iw dev | awk '$1=="Interface"{print $2}')"
ssid = true
speed_up = false
speed_down = false

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "uptime"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%e %B %Y - %H:%M:%S"
